replicaCount: 1

image:
  repository: siddharth67/solar-system:v3
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 80
  targetPort: 80
  nodePort: 30331

color:
  circle: green
  oval: green
  triangle: green
  rectangle: green
  square: green
