replicaCount: 1

image:
  repository: siddharth67/solar-system:v3
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 80
  targetPort: 80
  nodePort: 30330

color:
  circle: black
  oval: black
  triangle: black
  rectangle: black
  square: black
